env:
  browser: true
  node: true
  es2021: true
  jest: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
extends:
  - airbnb
  - airbnb/hooks
  - "plugin:prettier/recommended"
rules:
  consistent-return: off
  react/jsx-props-no-spreading: "off"
  react-hooks/exhaustive-deps: "warn"
  react-hooks/rules-of-hooks: "error"
  react/prop-types: "off"
  prettier/prettier: error
  no-magic-numbers:
    - error
    - ignore:
        - 0
        - 1
      ignoreDefaultValues: true
  import/extensions:
    - error
    - always
  no-use-before-define:
    - error
    - functions: false
      classes: false
      variables: false
      allowNamedExports: true
  no-underscore-dangle:
    - error